spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jbly?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: thwjd123