server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jbly?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: thwjd123

  jpa:
    database: mysql
    open-in-view: false # OSIV 설정
    hibernate: # application 실행 시 table create and drop
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: # 실행 시 어떤 쿼리가 발생하는지 확인하기 위한 설정
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always
      classpath: data.sql